
# Text for the article

introduction:
  main:
    - >
      👋 Hello! We are a team of computer science researchers. Thank you so much
      for taking your time to help us improve our tool, GAM Coach.
    - >
      You might have heard that some banks 🏦 are using Artificial Intelligence
      (AI) to decide whether a person can or cannot get a loan. These banks ask
      for the loan applicant's information, such as <u>annual income</u>,
      <u>employment length</u>, and <u>credit score</u>. Then, the banks use AI
      programs to go through all collected information and decide on whether to
      approve or reject this client's loan application.
    - >
      Unfortunately, many people's loan applications are rejected by these
      programs. 🙁 Therefore, we are developing GAM Coach, an interactive
      coaching tool to <strong>help these rejected loan applicants succeed in
      their future applications!</strong> 💪 To do that, GAM Coach identifies an
      applicant's current weakness and provides simple and customizable
      strategies to get their next loan application approved.
    - >
      In this task, we want you to <strong>pretend to be a person whose loan
      application is rejected by a bank</strong>. The bank points you to GAM
      Coach to help you improve and succeed in future applications.
  important:
    - >
      Please try your best to imagine that you are a real user—using GAM Coach
      to find the strategies that <strong>you think are useful</strong>. Our
      goal in this study is to learn what strategies would be helpful for real
      users and how GAM Coach can help.

tool:
  pre:
    - >
      GAM Coach is a web-based interactive tool that <strong>helps users
      identify strategies to obtain a desirable AI decision</strong> (e.g., loan
      application approval). These strategies can be "if you increase your FICO
      score (credit score) by 3 points, and increase your credit utilization by
      2.65%, you will get the loan."
  after:
    - >
      In this scenario, you are a loan applicant whose application is rejected
      by a bank. The bank then gives you a link to GAM Coach to help you improve
      and succeed in the next application. GAM Coach is pre-loaded with all
      "information" you provided to the bank, e.g., <code>annual income</code>,
      <code>employment length</code>, <code>FICO score</code> (credit score).
      Each piece of the information is called a "feature". For example,
      <code>FICO score</code> is one feature, and it has your value
      <code>650</code>.
    - >
      GAM Coach uses all these features and values to identify the best
      strategies that you can use to get the next loan. In addition, you can
      tell GAM Coach what features are easier to change than others. For
      example, maybe it's easier for you to change your <code>FICO score</code>
      than changing <code>employment length</code>, and maybe you only want to
      change <code>FICO Score</code> in a certain range. As you can see, these
      strategy preferences vary from user to user, so GAM Coach allows you to
      specify <strong>your own preference</strong> and generate personalized
      strategies <strong>just for you.</strong>

feature:
  main: >
    Please watch a walk-through tutorial video below to learn how a loan
    applicant can use GAM Coach.
  gap: >
    If you encounter any problems while using GAM Coach, you can click the link
    below to watch a shorter and more specific video explaining how each GAM
    Coach functionality works. You can also <a
    href="mailto:jayw@gatech.edu">email us</a>.
  list:
    - name: Change initial input values
      id: input
    - name: Explore different strategies to get a loan approval
      id: explore
    - name: >
        Experiment with different feature values to see how they affect the
        application decision
      id: value
    - name: Specify difficulty of different features
      id: difficulty
    - name: Specify the acceptable range of different features
      id: range
    - name: Generate new strategies that meet your preferences
      id: generate
    - name: Set the max number of features that plans can change
      id: max-num
    - name: Bookmark strategies you like and download a "receipt"
      id: download
    - name: Submit the HIT task
      id: submit

task:
  intro: >
    There are two tasks: (1) Learn how to use GAM Coach, follow the steps below
    and complete a short quiz on the Google survey; (2) Pretend to be a real
    user, and keep using GAM Coach until you find a strategy that you would be
    satisfied with if you were a rejected loan applicant.
  first: >
    By default, GAM Coach would load the information of Julia (Applicant #126)
    and provides suggestions for her to improve future applications. Please watch
    tutorial videos and complete the following steps.
  firstList:
    - >
      Julia is curious about the loan decision process, so she wants to play
      around with some values to learn how they would affect the loan decision.
    - >
      Click Plan 1, <strong>change the hypothetical value</strong> of <code>FICO
      score</code> to 662. <em>Answer question 1</em> on the Google survey.
    - >
      <strong>Reset</strong> your changes on <code>FICO score</code> by clicking
      the "reset" button (top right of the card).
    - >
      <strong>Try different hypothetical values</strong> of <code>Loan
      Purpose</code>. <em>Answer question 2</em> on the Google survey.
    - >
      <strong>Reset</strong> your changes on <code>Loan Purpose</code> by clicking
      the "reset" button.
    - >
      Browse Plan 1 to Plan 5. <em>Answer question 3</em> on the Google survey.
    - >
      Julia really wants to get the loan, but she is not willing to compromise
      the amount of loan she can get. Help her by <strong>setting the
      difficulty</strong> of <code>Loan Amount</code> to "impossible to change",
      so new plans won't change this feature.
    - >
      Click the "Regenerate" button on the top right to generate new plans.
      <em>Answer question 4</em> on the Google survey.
    - >
      Julia notices that not a single plan is changing her <code>Credit
      Utilization</code>! It is actually very easy for her to cut down the
      credit use to a lower range (e.g., 10% to 40%). <strong>Change the
      acceptable range</strong> of <code>Credit Utilization</code> to "from 10
      to 40". <strong>Change the difficulty</strong> of <code>Credit
      Utilization</code> to "very easy".
    - >
      Generate new plans. <em>Answer question 5</em> on the Google survey.
    - >
      Julia is planning to buy a condo this year, so changing the home ownership
      status is very easy. <strong>Change the acceptable range</strong> of
      <code>Home Ownership</code> to "Mortgage" and "Rent". <strong>Change the
      difficulty</strong> of <code>Home Ownership</code> to "very easy".
    - >
      Generate new plans. <em>Answer question 6</em> on the Google survey.
    - >
      Julia has found a lot of good strategies, but many of them require her to
      change multiple features. Julia wonders if it is possible to only change
      one feature to get the loan. <strong>Change the max number of features a
      plan can change</strong> to 1.
    - >
      Generate new plans. <em>Answer question 7</em> on the Google survey.
    - >
      <strong>Bookmark a plan</strong> (any plan) by clicking the star icon next
      to the plan name. <strong>Download a receipt</strong> and <em>Answer
      question 8</em> on the Google survey.
    - >
      You have completed Task 1. Proceed to the next section in your Google
      survey.
  main: >
    You are now a GAM Coach master, and it is your show time! In this task, you
    will <strong>pretend to be a real user</strong> and keep using GAM Coach
    until you find a strategy (or multiple strategies!) that you would be
    satisfied with if you were a loan applicant. You are free to set any
    preferences to fit your need. <strong>There are no a right answers</strong>,
    as the best strategy is different from person to person.
  gap: >
    Here are some concrete steps to help you get started:
  list:
    - item: >
        <strong>Click the refresh icon</strong> on the left side to change the
        initial input values to another random loan applicant's values. You
        <strong>cannot</strong> use Julia's info (Applicant #126) for Task 2.
      list: null
    - item: >
        <strong>Click the edit icon</strong> on the left side to view the
        current input values. To help you simulate the real-life use case, you
        can change any input values to mimic your real value or someone you
        know. You are <strong>required to change</strong> the input value of
        <strong>at least one feature</strong>.
      list: null
    - item: >
        Repeat step 1 and 2 until you find initial input values that you are
        comfortable with.
      list: null
    - item: >
        <strong>Imagine to be a real user</strong> and keep using GAM Coach
        until you find a set of strategies that you would pick if you were a
        rejected loan applicant.
      list:
        - >
          Remember to save plans you are interested in before generating new
          plans, because you won't be able to access old unsaved plans.
        - >
          You can remove a saved plan by clicking the "Bookmarks" button and
          then the "trash can" icon next to the plan name. It is helpful when
          you find better plans in new generations.
    - item: >
        Once you are satisfied with your bookmarked strategies, <strong>click
        the "I'm done" button</strong> on the right side. <strong>Rate and
        review</strong> your preferences and plans. Then, <strong>click the
        "submit" button</strong> to send your data to us. The data contains your
        interaction logs (e.g., clicks, hovering, drags), generated
        strategies, and all your reviews.
      list: null
    - item: >
        GAM Coach will generates a unique code (6-digit number) for you,
        <strong>copy and paste</strong> it in your Google survey.
      list: null
    - item: >
        <strong>Answer all questions</strong> in the Google survey and
        <strong>submit</strong> the survey.
      list: null
    - item: >
        <strong>Paste the code</strong> in MTurk page and
        <strong>submit</strong> it.
      list: null
    - item: >
        Done—thank you so much!
      list: null

  accept: >
    We will accept your HIT once (1) we have received your interaction log and
    strategy data, Google survey, HIT submission under the <strong> same
    verification code</strong>, (2) you have correctly answered all quiz
    questions, (3) Your interaction log shows that you have completed all
    required tasks.

  bonus:
    intro: >
      You will get a $1 bonus reward if your responses (interaction log, survey
      results, preference & plan reviews) show that you have <strong>tried your
      best</strong> to imagine to be a real user of GAM Coach to help us improve
      GAM Coach. You will get the bonus if your responses can score at least 10
      points, based on the following list:
    list:
      - >
        Your interaction log shows that you are engaged with the tool (+3
        points)
      - >
        Your explanations for preferences and plans are well-justified and
        convincing (+9 points)
      - >
        Your explanations show that you have put real effort to imagine to be a
        real user (+2 points)
      - >
        You provide specific feedback to improve GAM Coach or/and the HIT design
        (+ 5 points)
      - >
        You have noticed and reported some "strange" patterns of suggested plans
        (+ 9 points)

overview: >
  The tutorial video above will help you learn how to use GAM Coach and complete
  this HIT. Please don't replicate what the video does. We want you to imagine to
  be a real user and use GAM Coach to find strategies <strong>work for
  you.</strong>

detail: >
  We list a few more shorter videos that each explain one functionality of GAM
  Coach. You are not required to watch these videos. However, if you encounter
  any problems while using GAM Coach, you might find these videos helpful.

video:
  - header: Change initial input values
    video: input
    isWide: true
    text: >
      The default GAM Coach input is based on the information from a real
      rejected loan applicant. The initial values might be very different from
      your values. If it can help you imagine being a real user using GAM Coach,
      you can change the input values to mimic your values or someone you know.
  - header: Explore different strategies
    video: explore
    isWide: false
    text: >
      Every time you ask GAM Coach to generate strategies, it generates 5
      different plans for you. You can click the different tabs to compare and
      explore different plans. If you set some configurations to some feature
      under one tab, the configuration is synced to all other tabs
      automatically. <strong>You need to click the regenerate button to apply these new
      configurations.</strong>
  - header: Change feature values
    video: value
    isWide: false
    text: >
      You might want to try out some "hypothetical" values to see how the they
      would affect your loan decision score. Setting these values does not have
      any impact on you or new plan generations.
  - header: Specify difficulty
    video: difficulty
    isWide: false
    text: >
      GAM Coach tries to find the "best" strategy for users to succeed. However,
      the definition of "best" is different from one user to another. For
      example, maybe it is easier for you to change <code>FICO score</code> in
      real life, but it might be easier for your friend to change <code>Loan
      Amount</code> instead. Therefore, GAM Coach allows you to specify the
      difficulty to change a feature in real life. New plans will try to
      prioritize features that are easier for you to change and ignore features
      that are hard or impossible to change.
  - header: Specify acceptable range
    video: range
    isWide: false
    text: >
      Similar to difficulties, many users have an "acceptable range" of changes.
      For example, some user might be able to lower the <code>Loan Amount</code>
      in the next application, but they can only decrease it by $2000. They can
      tell GAM Coach the acceptable range by dragging sliders or clicking bars
      in the feature cards. New plans will make sure to meet your acceptable
      range.
  - header: Generate new strategies
    video: generate
    isWide: false
    text: >
      After setting difficulties and acceptable ranges for some features, you
      can click the "Regenerate" button to generate new plans that meet your
      constraints. You can keep fine-tuning your specifications and regenerating
      new plans until you find the strategies that work <strong>for
      you</strong>.
  - header: Max number of features that a plan can change
    video: max-num
    isWide: false
    text: >
      Some users prefer strategies that only change a few features. You can change
      the max number of features that a plan can change by clicking the drop
      down menu on the top right of the tool.
  - header: Bookmark strategies and download a receipt
    video: download
    isWide: false
    text: >
      Don't forget to save plans you like by clicking the star icon in the tab
      bar. It would save the plan to your Bookmarks. In the Bookmarks pop-up,
      You can also download a receipt. A receipt is a securely signed document
      that you can use as proof in your future applications: if you make the
      changes suggested by GAM Coach, the bank will guarantee you a loan
      approval.
  - header: Submit the HIT task
    video: submit
    isWide: true
    text: >
      After you find your favorite strategies, you can click the "I'm Done"
      button to submit. It would ask you to rate your preferences and plans.
      Please provide detailed explanations. Next, GAM Coach will show you a
      unique 6-digit verification code. You need to copy the code in the Google
      Survey and the HIT page.

